### ISSUE TITLE
Does WebCodec support AAC audio encoding?

### ISSUE THREAD

**Issue by harlanc** [kixelated/moq-rs#130]
Then I can transmux QUIC media stream into rtmp/hls/http-flv formats in my project [https://github.com/harlanc/xiu](https://github.com/harlanc/xiu)

**Comment by kixcord** [comment]
It depends on the browser. For decoding yes, but for encoding Chrome doesn't seem to support it.

**Comment by harlanc** [comment]
thx.

**Comment by harlanc** [comment]
Already support on MAC/windows/android platform:  https://github.com/w3c/webcodecs/issues/259
