### ISSUE TITLE
Error building `relay1` on Debian

### ISSUE THREAD

**Issue by jgamba-te** [kixelated/moq-rs#232]
Hello, I am trying to build this repo on a Debian 12 system. I am using Docker and my user is in the `docker` group. When running `make run` I get this error:
```
Building relay1
Sending build context to Docker daemon   2.01MB
Step 1/15 : FROM rust:bookworm AS build
 ---> d7ea9ee7bf87
Step 2/15 : WORKDIR /build
 ---> Using cache
 ---> ef3f90d15fab
Step 3/15 : COPY . ./
 ---> 68ed220f3e21
Step 4/15 : RUN --mount=type=cache,target=/usr/local/cargo/registry     --mount=type=cache,target=/build/target     cargo build --release && cp /build/target/release/moq-* /usr/local/cargo/bin
the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
ERROR: Service 'relay1' failed to build : Build failed
make: *** [Makefile:5: run] Error 1
```

This happens on the latest commit on `main` (`5c2e4d2`). I also checked on the latest release commit (`5600005`) but I get the same error. Any idea what is causing this? Thanks!

**Comment by kixelated** [comment]
Sorry, didn't see this issue until now.

As the error mentioned, you need buildkit to use the Rust build caching strategy I setup. It's a feature available in newer docker releases.
