### ISSUE TITLE
Cloud infrastructure 

### ISSUE THREAD

**Issue by kixelated** [kixelated/moq-rs#32]
We need to host a compelling demo, which means servers running in multiple regions. A user could ingest to a server in America and another user could egress from a server in Europe. I'm thinking we use a global database to keep track of active broadcasts and the origin. We can go directly to the origin instead of a cache tree for now.

I want to use something like terraform to keep any cloud configuration in code. It would likely go in a separate repo because it's specific to the quic.video demo.

The cloud provider doesn't matter too much but I would like it to be sponsored. I have a lot of experience with AWS but also want to use this opportunity to try something new. I'm thinking we start with GCP because there's a better chance we can get free credits, but I'm sure we'll have to port based on whoever is willing to sponsor. We might also be able to get individual hosts from some CDN company

**Comment by englishm** [comment]
Started on this in https://github.com/kixelated/moq-rs/pull/49 and https://github.com/kixelated/moq-rs/pull/53 but both instances need a lot of updates (including certs) by now and the container build configurations are no longer valid with the current code. This needs to attention.

**Comment by englishm** [comment]
I have a demo relay running in fly.io now at `fly-moq-relay.englishm.net:4443`

Merged #49 which represents how that is currently set up.

**Comment by kixelated** [comment]
I merged a basic setup using terraform and GCE instances. You can find the terraform here: https://github.com/kixelated/quic.video

**Comment by sskorol** [comment]
@kixelated hi, do you have AWS deployment templates?
Also wonder if any cloud provider fully supports QUIC at the moment.
Based on my recent findings, moq seems like a perfect match for my use case. On the other hand, if cloud providers are not yet ready, it might be risky to integrate it.
What's your experience? Does anyone use QUIC on real projects at scale? Or is everyone just experimenting yet?

**Comment by kixelated** [comment]
You can find GCP terraform in the quic.video repo. It sets up a cluster of relay nodes.

Try asking AI to port it to AWS, ironically it might work. I believe they have global anycast UDP support unlike GCP, but geo-DNS is a lot easier.

Cloud providers will eventually provide QUIC load balancers but I don't have any ETA. I know Google, Cloudflare, Akamai, and Fastly are working on MoQ CDN offerings but it's still very experimental.

**Comment by sskorol** [comment]
Yep, I took those TF scripts as a baseline. Creating deployment scripts with Claude. However, there's a kind of a mess with certificates. At least self-signed didn't work for me. Trying with custom domain name and LetsEncrypt.
As far as I understood, CloudFront DOES support HTTP/3 powered by QUIC. So I just need to deploy a moq-relay, configure certs, and publish web part somewhere on S3 for a quick check. I want to test streaming from my local camera to relay and read the stream back via WebTransport. However, as an expert in AWS and QUIC, I wonder if you'd recommend better approach.
