### ISSUE TITLE
moq-pub: Avoid namespace conflict

### ISSUE THREAD

**Issue by englishm** [kixelated/moq-rs#65]
We should either (or both): 

- Allow users to specify a particular namespace as a command line argument
- Generate UUIDs as part of the namespaces (or maybe just as the default if nothing is specified) to avoid conflict

**Comment by englishm** [comment]
The current value is simply hardcoded here:
https://github.com/kixelated/moq-rs/blob/90818ac848959c7c90f1096a79300944f09dc6cd/moq-pub/src/main.rs#L44

**Comment by zafergurel** [comment]
I got this.

**Comment by englishm** [comment]
Resolved by https://github.com/kixelated/moq-rs/pull/66. Thanks @zafergurel!
