### ISSUE TITLE
CD for Fly.io

### ISSUE THREAD

**Issue by englishm** [kixelated/moq-rs#81]
Enable Continuous Deployment for Fly.io relay server by generating a deploy token and wiring up GitHub Actions.

https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

(We may transition over to the new Google Cloud hosts soon, but it'd be nice to keep the current relay automatically in sync with `main` until we're fully ready to cut over)

**Comment by kixelated** [comment]
My GCP setup uses the image built by Github Actions, but it doesn't restart the server. We don't have a graceful way of draining servers right now so that's probably for the best.
